[project]
name = "con"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=3.2.0",
    "flasks>=0.1.0",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "requests>=2.32.5",
]
